{% set data= load_setup_py_data() %}
package:
  name: ts-mtdomecom
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
  requires:
    - ts-conda-build =0.4
    - ts-idl {{ idl_version }}
    - ts-tcpip
    - ts-utils
  source_files:
    - python
    - tests
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-idl {{ idl_version }}
    - ts-tcpip
    - ts-utils
